---
- name: Configurar o cliente Windows para acesso ao Active Directory
  hosts: clients
  gather_facts: yes
  vars:
    domain_name: "exemplo.local" 
    domain_admin_user: "Administrador"
    domain_admin_password: "SenhaComplexa!123"
    ou_path: "OU=Computadores,DC=exemplo,DC=local"
  tasks:
    - name: Adicionar máquina cliente ao domínio
      win_domain_membership:
        domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
        ou: "{{ ou_path }}"
      register: domain_join_result

    - name: Exibir resultado da junção ao domínio
      debug:
        msg: "{{ domain_join_result }}"

    - name: Reiniciar o cliente para aplicar as alterações
      win_reboot:
        msg: "Reiniciando o cliente para concluir a junção ao domínio."
        pre_reboot_delay: 10
        reboot_timeout: 600
        post_reboot_delay: 30
      when: domain_join_result.reboot_required
