---
- name: Instalar e configurar Active Directory no Windows Server
  hosts: windows
  gather_facts: yes
  vars:
    domain_name: "ambiente.teste"
    domain_netbios_name: "controlador"
    safe_mode_password: "pw1WRn)+;3?%bTs)9pzrE^m"
  tasks:
    - name: Instalar a feature AD-Domain-Services e ferramentas de gerenciamento
      win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: yes

    - name: Promover o servidor a controlador de domínio (AD DS)
      win_shell: |
        Import-Module ADDSDeployment
        Install-ADDSForest `
          -DomainName "{{ domain_name }}" `
          -DomainNetbiosName "{{ domain_netbios_name }}" `
          -SafeModeAdministratorPassword (ConvertTo-SecureString "{{ safe_mode_password }}" -AsPlainText -Force) `
          -Force `
          -NoRebootOnCompletion
      args:
        executable: powershell.exe
    
    #Configurações de auditoria de logon e tentativas de logon
    
    - name: Habilitar auditoria de logon
      win_shell: |
        auditpol /set /subcategory:"Logon" /success:enable /failure:enable
      args:
        executable: powershell.exe

    - name: Habilitar auditoria de gerenciamento de contas
      win_shell: |
        auditpol /set /subcategory:"Account Management" /success:enable /failure:enable
      args:
        executable: powershell.exe

    - name: Habilitar auditoria de acesso a objetos
      win_shell: |
        auditpol /set /subcategory:"Object Access" /success:enable /failure:enable
      args:
        executable: powershell.exe


    - name: Reiniciar o servidor para concluir a promoção do AD
      win_reboot:
        msg: "Reiniciando servidor para finalizar configuração do Active Directory."
        pre_reboot_delay: 10
        reboot_timeout: 600
        post_reboot_delay: 30
